[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-builder = "0.20"
bon = "2.3"
buildstructor = "0.5"
derive_builder = "0.20"
const_typed_builder = "0.3.0"
typestate-builder = "0.1.1"
